feat: automate CHANGELOG date updates and implement pre-commit file validation in build and release scripts

diff --git a/scripts/build b/scripts/build
--- a/scripts/build
+++ b/scripts/build
@@ -83,6 +83,12 @@ else
         pypi_version=$new_version
     fi
 
+    sed -e "s/\[Unreleased\]/[${new_version}] - $(date +"%Y-%m-%d")/" -i CHANGELOG.md
+    if ! grep -q "\[${new_version}\] - $(date +"%Y-%m-%d")" CHANGELOG.md; then
+        echo -e "${RED}>>> Build CANCELLED: ${ORANGE}Failed to update CHANGELOG.md${NC}"
+        exit
+    fi
+
     sed -e "s/^__version__ = \".*\"/__version__ = \"$new_version\"/g" -i sigenergy2mqtt/config/version.py
     date "+%Y-%m-%d %H:%M:%S,000 INFO     sigenergy2mqtt:build..........0044 Updated version from $old_version to $new_version (PyPi=$pypi_version)"
 fi
